{% set name = "openscm-units" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ab8c5a12048ba73f3e76115af716454bd762db5a5fc1ce1287d3b2ab01b3de0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - pandas
    - pint

test:
  imports:
    - openscm_units

  commands: python -c "import openscm_units; ur = openscm_units.unit_registry; ur.enable_contexts('AR5GWP100'); assert openscm_units.__version__ == '{{ version }}'"

about:
  home: https://github.com/openscm/openscm-units
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Units for use with simple climate modelling
  doc_url: https://openscm-units.readthedocs.io/en/latest/
  dev_url: https://github.com/openscm/openscm-units

extra:
  recipe-maintainers:
    - znicholls
    - lewisjared
