{% set name = "openscm-units" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9e199ee3356cb5ce4f95a11b13d5411cd172c108bb76267be052070947e9aef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - globalwarmingpotentials
    - pandas
    - pint

test:
  imports:
    - openscm_units
  requires:
    - pip
  commands:
    - pip check
    - python -c "import openscm_units; ur = openscm_units.unit_registry; ur.enable_contexts('AR5GWP100'); assert openscm_units.__version__ == '{{ version }}'"

about:
  home: https://github.com/openscm/openscm-units
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Units for use with simple climate modelling
  doc_url: https://openscm-units.readthedocs.io/en/latest/
  dev_url: https://github.com/openscm/openscm-units

extra:
  recipe-maintainers:
    - znicholls
    - lewisjared
