{% set name = "openscm-units" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2352df48af204bdb6dd60db36cb22b968f574c683dc11fc07a54d9ab4e9036b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas
    - pint

test:
  imports:
    - openscm_units

  commands: python -c "import openscm_units; assert openscm_units.__version__ == '{{ version }}'"

about:
  home: https://github.com/openscm/openscm-units
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Units for use with simple climate modelling
  doc_url: https://openscm-units.readthedocs.io/en/latest/
  dev_url: https://github.com/openscm/openscm-units

extra:
  recipe-maintainers:
    - znicholls
    - lewisjared
